


services:

  node-app:
    image: hhhhhwan/Crud_web_image
    ports:
      - 2200:2200  
    container_name: CRUD-container
  environment:
    GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
    GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    SESSION_SECRET: ${SESSION_SALT_SECRETS}
    DB_USER_NAME: ${DB_MYSQL_USERNAME}
    DB_USER_PASS: ${DB_MYSQL_PASSWORD}
    DB_DATA_NAME: ${DB_MYSQL_DATABASE}

  network :
    - web-services
  depends_on:
    DB:
      condition: service_healthy
    DB_redis:
      condition: service_healthy
  

  DB:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_ROOTPASSWORD}
      MYSQL_DATABASE: ${DB_MYSQL_DATABASE}
      MYSQL_USER: ${DB_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
    container_name: mysql-container
    user: root
    ports:
      - 2201:3306
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - web-services
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  DB_redis:
    image: redis
    container_name: redis-container
    user: root
    ports:
      - 6379:6379
    networks:
      - web-services
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 5
      
  
  networks:
    web-services:
      driver: bridge
      name: web-services