name: CI with docker image build

on :
 push:
  branches:
    - main

jobs:
  docker-build-and-push:
    name : build and push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/community_web_images:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/community_web_images:latest
      
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ACTION_SSH_HOST }}
          username: ${{ secrets.ACTION_SSH_USER }}
          key: ${{ secrets.ACTION_SSH_KEY }}
          port: ${{ secrets.ACTION_SSH_PORT }}
          script: |
            mkdir test_check
            echo "connected success CICD test"
            echo $PWD

      - name: Verify Deployment
        run: |
          echo "Deployment to PROD environment successful!"
  





